services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_MYORIGIN_API_URL=https://api.myorigin.net
        - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    env_file:
      - .env.local
