export const Routes = {
  Home: "/home",
  Login: "/login",
  Tasks: "/tasks",
  TasksRepair: "/tasks/repair",
  TasksRepairDetail: (id: string) => `/tasks/repair/${id}`,
  TasksRepairCallCenter: "/tasks/repair/call-center",
  TasksRepairCreate: "/tasks/repair/create",
  TasksRepairCalendar: "/tasks/repair/calendar",
  TasksJuristicService: "/tasks/juristic/service",
  TasksJuristicCentral: "/tasks/juristic/central",
  Dashboard: "/dashboard",
  Admin: "/admin",
  AdminUsers: "/admin/user",
  AdminRoles: "/admin/role",
  System: "/system",
};
